import Head from "next/head";
import AboutPage from "../components/views/AboutPage/AboutPage";

const AboutUs = () => {
  return (
    <div>
      <Head>
        <title>Tech-Introspectors / About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen">
        <AboutPage />
      </main>
    </div>
  );
};

export default AboutUs;
