import Head from "next/head";
import ContactPage from "../components/views/ContactPage/ContactPage";

const ContactUs = () => {
  return (
    <div>
      <Head>
        <title>Tech-Introspectors / About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen">
        <ContactPage />
      </main>
    </div>
  );
};

export default ContactUs;
