import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tech-Introspectors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center items-center h-screen text-4xl">
        Home page
      </div>
    </div>
  );
}
