import Head from "next/head";
import Hero from "../components/Homepage/Hero";
import OurTopProjects from "../components/Homepage/OurTopProjects";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tech-Introspectors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <OurTopProjects />
    </div>
  );
}
